//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.1
//     from Assets/HotasInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @HotasInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @HotasInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""HotasInput"",
    ""maps"": [
        {
            ""name"": ""Hotas"",
            ""id"": ""6d133562-5938-4be1-9de4-07f934ae73cf"",
            ""actions"": [
                {
                    ""name"": ""Trigger"",
                    ""type"": ""Button"",
                    ""id"": ""7085e214-c178-4c5e-89e2-bfee17d2686f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AIm"",
                    ""type"": ""Value"",
                    ""id"": ""52f2d188-40a4-446d-9bcd-c62fbe02b7e7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Drive"",
                    ""type"": ""Value"",
                    ""id"": ""be08ac82-da51-48a5-9507-42a1ea28865a"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Turn"",
                    ""type"": ""Value"",
                    ""id"": ""c4d2c920-db15-4946-ab33-bf996d4d52a8"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Strafe"",
                    ""type"": ""Value"",
                    ""id"": ""5a81eb3f-a1fe-459d-898e-a7d79289e8e6"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fea44f19-5b1a-43a5-a25e-3bbbe5318916"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4f67fce-8363-46d9-88ac-834fd17fa424"",
                    ""path"": ""<Joystick>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82f3022e-e416-4dbd-974b-78a647fdb8e5"",
                    ""path"": ""<Joystick>/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AIm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30808d38-71ae-4f6f-a0bf-fef6246f7175"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AIm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dcfeb529-9a4e-4c7a-8dc2-189da333974f"",
                    ""path"": ""<HID::Thrustmaster T.Flight Hotas X>/z"",
                    ""interactions"": """",
                    ""processors"": ""Invert"",
                    ""groups"": """",
                    ""action"": ""Drive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""748f2e33-f2cd-4685-a05b-41cf2ed4c2c7"",
                    ""path"": ""<Gamepad>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8c031cc-6d70-4fce-bda0-344d62baa92b"",
                    ""path"": ""<HID::Thrustmaster T.Flight Hotas X>/rz"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a2fd27a-b00a-4796-80d7-73b3fc239090"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""629b9b63-7819-4661-babe-82093ed2df34"",
                    ""path"": ""<HID::Thrustmaster T.Flight Hotas X>/slider"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Strafe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""48eb3c21-caa7-463f-94ea-31148d4d6468"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Strafe"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""bf9fd066-0097-4f25-b198-5aa67e5ada48"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Strafe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""51f41f0a-52ed-4e60-a5e7-afd529ced774"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Strafe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Hotas
        m_Hotas = asset.FindActionMap("Hotas", throwIfNotFound: true);
        m_Hotas_Trigger = m_Hotas.FindAction("Trigger", throwIfNotFound: true);
        m_Hotas_AIm = m_Hotas.FindAction("AIm", throwIfNotFound: true);
        m_Hotas_Drive = m_Hotas.FindAction("Drive", throwIfNotFound: true);
        m_Hotas_Turn = m_Hotas.FindAction("Turn", throwIfNotFound: true);
        m_Hotas_Strafe = m_Hotas.FindAction("Strafe", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Hotas
    private readonly InputActionMap m_Hotas;
    private List<IHotasActions> m_HotasActionsCallbackInterfaces = new List<IHotasActions>();
    private readonly InputAction m_Hotas_Trigger;
    private readonly InputAction m_Hotas_AIm;
    private readonly InputAction m_Hotas_Drive;
    private readonly InputAction m_Hotas_Turn;
    private readonly InputAction m_Hotas_Strafe;
    public struct HotasActions
    {
        private @HotasInput m_Wrapper;
        public HotasActions(@HotasInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Trigger => m_Wrapper.m_Hotas_Trigger;
        public InputAction @AIm => m_Wrapper.m_Hotas_AIm;
        public InputAction @Drive => m_Wrapper.m_Hotas_Drive;
        public InputAction @Turn => m_Wrapper.m_Hotas_Turn;
        public InputAction @Strafe => m_Wrapper.m_Hotas_Strafe;
        public InputActionMap Get() { return m_Wrapper.m_Hotas; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HotasActions set) { return set.Get(); }
        public void AddCallbacks(IHotasActions instance)
        {
            if (instance == null || m_Wrapper.m_HotasActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_HotasActionsCallbackInterfaces.Add(instance);
            @Trigger.started += instance.OnTrigger;
            @Trigger.performed += instance.OnTrigger;
            @Trigger.canceled += instance.OnTrigger;
            @AIm.started += instance.OnAIm;
            @AIm.performed += instance.OnAIm;
            @AIm.canceled += instance.OnAIm;
            @Drive.started += instance.OnDrive;
            @Drive.performed += instance.OnDrive;
            @Drive.canceled += instance.OnDrive;
            @Turn.started += instance.OnTurn;
            @Turn.performed += instance.OnTurn;
            @Turn.canceled += instance.OnTurn;
            @Strafe.started += instance.OnStrafe;
            @Strafe.performed += instance.OnStrafe;
            @Strafe.canceled += instance.OnStrafe;
        }

        private void UnregisterCallbacks(IHotasActions instance)
        {
            @Trigger.started -= instance.OnTrigger;
            @Trigger.performed -= instance.OnTrigger;
            @Trigger.canceled -= instance.OnTrigger;
            @AIm.started -= instance.OnAIm;
            @AIm.performed -= instance.OnAIm;
            @AIm.canceled -= instance.OnAIm;
            @Drive.started -= instance.OnDrive;
            @Drive.performed -= instance.OnDrive;
            @Drive.canceled -= instance.OnDrive;
            @Turn.started -= instance.OnTurn;
            @Turn.performed -= instance.OnTurn;
            @Turn.canceled -= instance.OnTurn;
            @Strafe.started -= instance.OnStrafe;
            @Strafe.performed -= instance.OnStrafe;
            @Strafe.canceled -= instance.OnStrafe;
        }

        public void RemoveCallbacks(IHotasActions instance)
        {
            if (m_Wrapper.m_HotasActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IHotasActions instance)
        {
            foreach (var item in m_Wrapper.m_HotasActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_HotasActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public HotasActions @Hotas => new HotasActions(this);
    public interface IHotasActions
    {
        void OnTrigger(InputAction.CallbackContext context);
        void OnAIm(InputAction.CallbackContext context);
        void OnDrive(InputAction.CallbackContext context);
        void OnTurn(InputAction.CallbackContext context);
        void OnStrafe(InputAction.CallbackContext context);
    }
}
